[Amibe] Validate XML file instead of DOM tree
There are trouble with some JAXP implementations (for instance
when run friom jython) which throw an exception:
org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'jcae'.